insitu_features1 = [
    'SDH1PS01_gw-depth_m',
    'ATMOS41_precipitation_mm',
    # 'ATMOS41_solar-radiation_Wm2',
    # 'ATMOS41_wind-speed_ms',
    # 'ATMOS41_air-temperature_degreeC',
    # 'TEROS12-05cm_water-content_m3m3',
    # 'TEROS12-05cm_soil-temperature_degreeC',
    # 'TEROS12-05cm_saturation-extract-ec_mScm',
    # 'TEROS12-15cm_water-content_m3m3',
    # 'TEROS12-15cm_soil-temperature_degreeC',
    # 'TEROS12-15cm_saturation-extract-ec_mScm',
    # 'TEROS12-30cm_water-content_m3m3',
    # 'TEROS12-30cm_soil-temperature_degreeC',
    # 'TEROS12-30cm_saturation-extract-ec_mScm',
    # 'TEROS12-48cm_water-content_m3m3',
    # 'TEROS12-48cm_soil-temperature_degreeC',
    # 'TEROS12-48cm_saturation-extract-ec_mScm',
    # 'TEROS21-25cm_soil-temperature_degreeC',
    # 'TEROS21-35cm_soil-temperature_degreeC',
]

insitu_features2 = [
    'SDH2PP01_gw-depth_m',
    # 'SDH2PS02_gw-depth_m',
    # 'ATMOS41_precipitation_mm',
    # 'ATMOS41_solar-radiation_Wm2',
    # 'ATMOS41_wind-speed_ms',
    # 'ATMOS41_air-temperature_degreeC',
    # 'TEROS12-18cm_water-content_m3m3',
    # 'TEROS12-18cm_soil-temperature_degreeC',
    # 'TEROS12-18cm_saturation-extract-ec_mScm',
    # 'TEROS12-45cm_water-content_m3m3',
    # 'TEROS12-45cm_soil-temperature_degreeC',
    # 'TEROS12-45cm_saturation-extract-ec_mScm',
    # 'TEROS12-65cm_water-content_m3m3',
    # 'TEROS12-65cm_soil-temperature_degreeC',
    # 'TEROS12-65cm_saturation-extract-ec_mScm',
    # 'TEROS21-31cm_soil-temperature_degreeC',
    # 'TEROS21-55cm_soil-temperature_degreeC',
]

remote_features = [
    # 'B2_mean',
    # 'B3_mean',
    # 'B4_mean',
    # 'B5_mean',
    # 'B6_mean',
    # 'B7_mean',
    # 'B8_mean',
    # 'B8A_mean',
    # 'B11_mean',
    # 'B12_mean',
    'ndvi_mean',
    # 'gndvi_mean',
    # 'ndwi_mean',
    # 'mndwi_mean',
    # 'ndmi_mean',
    # 'ndmi2_mean',
    # 'str1_mean',
    'str2_mean',
    # 'brightness_mean',
    # 'greenness_mean',
    # 'wetness_mean'
]

# List of variables to exclude from z-score filtering
no_outlier_check = ['ATMOS41_precipitation_mm']